baseURL = "https://blog.sayakachan.net/"
languageCode = "ja-jp"
title = "さやかちゃんドットネット"
theme = "hyde"

[params]
  description = "Web系企業で決済インフラのエンジニアとして働いています。"
  themeColor = "theme-base-0a"

[Menus]
  main = [
      {Name = "Portfolio", URL = "https://sayakachan.net/"},
  ]

[markup.goldmark.renderer]
  unsafe = true
