baseURL = "https://blog.sayakachan.net/"
languageCode = "en-us"
title = "blog.sayakachan.net"
theme = "hyde"

[params]
  description = "とある情報系学生のブログです。"
  themeColor = "theme-base-0a"

[Menus]
  main = [
      {Name = "Portfolio", URL = "https://sayakachan.net/"},
  ]

[markup.goldmark.renderer]
  unsafe = true
