version: 2

jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - run: 
          name: Echo hugo version
          command: echo "$(hugo version)"
      - add_ssh_keys:
          fingerprints:
            - 17:dc:da:65:06:ee:39:bd:ec:4c:bf:d2:31:9b:75:80
      - checkout
      - run:
          name: Generate static files in 'public' dir
          command: hugo -v
      - run:
          name: Deploy static files to gh-pages branch
          command: ./.circleci/deploy.sh
